name: babyhub
description: An E-commerce app for baby Products

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

  # Utility Packages


dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  #  flutter_native_splash: ^2.3.2

#Firebase

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1


  #Icons
  #  icons-ax: ^0.0.8
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  cached_network_image: ^3.3.1

#PACKAGES END
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_images/login.png
    - assets/images/onboarding_images/success.png
    -  assets/images/onboarding_images/page1.gif
    - assets/images/onboarding_images/order.png
    - assets/images/onboarding_images/search.png
    - assets/images/onboarding_images/welcome.png
    - assets/images/onboarding_images/image2.jpg
    - assets/images/onboarding_images/image3.jpg
    - assets/images/banner/
    - assets/images/product_images/
    - assets/logo/
    - assets/categories/
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-Bold.ttf
        - asset: assets/font/Lexend-Medium.ttf
          weight: 500
        - asset: assets/font/Lexend-Light.ttf
          weight: 300
        - asset: assets/font/Lexend-ExtraBold.ttf
        - asset: assets/font/Lexend-Regular.ttf
          weight: 500
        - asset: assets/font/Lexend-SemiBold.ttf
          weight: 700
        - asset: assets/font/Lexend-Black.ttf
          weight: 900



#    -assets/logo/BabyHub.png


